DELIMITER //
CREATE TRIGGER `TRGR_EDC_RSVN_INFO_BEFORE_INSERT` BEFORE INSERT ON `EDC_RSVN_INFO` FOR EACH ROW
BEGIN

	/* 변수 선언 */
	DECLARE v_msg VARCHAR(2000);
	DECLARE v_apply_cnt DECIMAL(3);
	DECLARE v_edc_rsvn_no VARCHAR(20);
	DECLARE v_edc_stat VARCHAR(4);

	DECLARE v_capa_dvdyn VARCHAR(3);
	DECLARE v_tot_capa DECIMAL(3);
	DECLARE v_on_capa DECIMAL(3);
	DECLARE v_off_capa DECIMAL(3);
	DECLARE v_endwait_capa DECIMAL(3); -- 선착대기 정원

	DECLARE v_tot_regi_cnt DECIMAL(3);
	DECLARE v_on_regi_cnt DECIMAL(3);
	DECLARE v_off_regi_cnt DECIMAL(3);
	DECLARE v_tot_waiting_cnt DECIMAL(3); -- 현재 대기인원

	DECLARE v_rsvn_rectype VARCHAR(4);

	DECLARE v_ctgr_nm VARCHAR(2000);
	DECLARE v_limit_cnt DECIMAL(3);


	/* 1.중복등록체크 */
	IF NEW.EDC_RSVN_MEMTYPE = '1001' THEN -- 회원
		SELECT EDC_RSVN_NO, EDC_STAT INTO v_edc_rsvn_no, v_edc_stat
			FROM EDC_RSVN_INFO
			WHERE COMCD = NEW.COMCD
				AND EDC_PRGMID = NEW.EDC_PRGMID
				AND EDC_RSVNSET_SEQ = NEW.EDC_RSVNSET_SEQ
				AND EDC_RSVN_MEMNO = NEW.EDC_RSVN_MEMNO /*회원번호*/
				AND EDC_STAT IN ('1000', '1002', '2001', '4001');
	ELSE -- 2001(비회원)
		SELECT EDC_RSVN_NO, EDC_STAT INTO v_edc_rsvn_no, v_edc_stat
			FROM EDC_RSVN_INFO
			WHERE COMCD = NEW.COMCD
				AND EDC_PRGMID = NEW.EDC_PRGMID
				AND EDC_RSVNSET_SEQ = NEW.EDC_RSVNSET_SEQ
				AND EDC_RSVN_CUSTNM = NEW.EDC_RSVN_CUSTNM /*비회원입력값*/
				AND EDC_RSVN_MOBLPHON = NEW.EDC_RSVN_MOBLPHON /*비회원입력값*/
				AND EDC_STAT IN ('1000', '1002', '2001', '4001');
	END IF;

	IF LENGTH(v_edc_rsvn_no) > 5 THEN
		SET v_msg = CONCAT('RSVN이미 예약 신청이 되어있습니다.|', v_edc_rsvn_no, '|', v_edc_stat);
	 	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
	END IF;

	/* 2.1 잔여인원체크(마감여부), 온라인정원, 오프라인정원조회 */
	SELECT A.EDC_CAPA_DVDYN, B.EDC_PNCPA, B.EDC_ONCAPA, B.EDC_OFFCAPA, B.EDC_ENDWAIT_CAPA, B.EDC_RSVN_RECTYPE
			INTO v_capa_dvdyn, v_tot_capa, v_on_capa, v_off_capa, v_endwait_capa, v_rsvn_rectype
		FROM EDC_PROGRAM A
			, EDC_RSVNSET_INFO B
		WHERE B.COMCD = NEW.COMCD
			AND B.EDC_PRGMID = NEW.EDC_PRGMID
			AND B.EDC_RSVNSET_SEQ = NEW.EDC_RSVNSET_SEQ
			AND A.COMCD = B.COMCD
			AND A.EDC_PRGMID = B.EDC_PRGMID;

	/* 2.2 on(10), off(20) 등록인원조회 */
	SELECT
		SUM(CASE WHEN EDC_ONOFFINTYPE = '10' AND EDC_STAT IN ('2001','4001')  THEN EDC_VISTNMPR ELSE 0 END) AS ON_REGI_CNT
		, SUM(CASE WHEN EDC_ONOFFINTYPE = '20' AND EDC_STAT IN ('2001','4001')  THEN EDC_VISTNMPR ELSE 0 END) AS OFF_REGI_CNT
		, SUM(CASE WHEN EDC_STAT IN ('2001','4001') THEN  EDC_VISTNMPR ELSE 0 END) AS TOT_REGI_CNT
		, SUM(CASE WHEN EDC_STAT IN ('1000')  THEN EDC_VISTNMPR ELSE 0 END) AS TOT_WAITING_CNT
		INTO v_on_regi_cnt, v_off_regi_cnt, v_tot_regi_cnt, v_tot_waiting_cnt
	FROM EDC_RSVN_INFO
	WHERE 1 = 1
		AND COMCD = NEW.COMCD
		AND EDC_PRGMID = NEW.EDC_PRGMID
		AND EDC_RSVNSET_SEQ = NEW.EDC_RSVNSET_SEQ;

	/* 2.3 온라인, 오프라인 정원체크: 선착접수와 선착대기만. 추첨은 체크 대상 아님 */
	IF (v_rsvn_rectype = '1001' OR v_rsvn_rectype = '1002') AND NEW.EDC_STAT IN ('2001','4001') THEN -- 선착접수
		IF v_capa_dvdyn = 'Y' THEN
			IF NEW.EDC_ONOFFINTYPE = 'ON' AND v_on_regi_cnt >= v_on_capa THEN
				SET v_msg = REPLACE('RSVN접수 인원이 마감되었습니다. 온라인 정원(CAPA명) 초과.', 'CAPA', v_on_capa);
				SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
			END IF;

			IF NEW.EDC_ONOFFINTYPE = 'OFF' AND v_off_regi_cnt >= v_off_capa THEN
				SET v_msg = REPLACE('RSVN접수 인원이 마감되었습니다. 오프라인 정원(CAPA명) 초과.', 'CAPA', v_off_capa);
				SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
			END IF;
		ELSE
			IF (v_on_regi_cnt + v_off_regi_cnt) >= v_tot_capa THEN
				SET v_msg = REPLACE('RSVN접수 인원이 마감되었습니다. 정원(CAPA명) 초과.', 'CAPA', v_tot_capa);
				SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
			END IF;
		END IF;
	END IF;

	IF v_rsvn_rectype = '1002' THEN -- 선착대기
		IF v_tot_regi_cnt >= v_tot_capa AND v_tot_waiting_cnt >= v_endwait_capa THEN
			SET v_msg = REPLACE(REPLACE('RSVN접수 인원(대기정원포함)이 마감되었습니다. 정원(CAPA명)+대기정원(WAIT명) 초과.', 'CAPA', v_tot_capa), 'WAIT', v_endwait_capa);
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
		END IF;
	END IF;



	/* 3.1 전체프로그램적용. 신청제한 */
	WITH T AS (
		SELECT A.COMCD, A.ORG_NO, A.EDC_RSVNLIMIT_CNT, A.EDC_RSVNLIMIT_PD, P.EDC_PRGMID
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(B.EDC_SDATE, 1, 6), '01')
					ELSE CONCAT(SUBSTR(B.EDC_SDATE, 1, 4), '0101')
				END AS SYYYYMMDD
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(B.EDC_SDATE, 1, 6), '31')
					ELSE CONCAT(SUBSTR(B.EDC_SDATE, 1, 4), '1231')
				END AS EYYYYMMDD
			FROM EDC_PROGRAM P, EDC_PROGRAM_LIMIT A, EDC_RSVNSET_INFO B
				WHERE B.COMCD = NEW.COMCD
					AND B.EDC_PRGMID = NEW.EDC_PRGMID
					AND B.EDC_RSVNSET_SEQ = NEW.EDC_RSVNSET_SEQ
					AND P.COMCD = B.COMCD
					AND P.EDC_PRGMID = B.EDC_PRGMID
					AND A.COMCD = P.COMCD
					AND A.ORG_NO = P.ORG_NO
					AND A.EDC_RSVNLIMIT_YN = 'Y'
					AND A.EDC_RSVNLMIT_GBN IN ('1001') /*1001:전체프로그램*/
	)
	SELECT NVL(T.EDC_RSVNLIMIT_CNT, 999), (NVL(SUM(EDC_VISTNMPR), 0)+1) INTO v_limit_cnt, v_apply_cnt /* + 1은 이번신청건 포함 */
		FROM T, EDC_RSVN_INFO X, EDC_PROGRAM Y
		WHERE 1 = 1
			AND X.COMCD = T.COMCD
			AND X.EDC_STAT IN ('1000', '1002', '2001', '4001')
			AND CASE WHEN X.EDC_RSVN_MEMTYPE = '1001'/*회원*/ THEN X.EDC_MEM_NO = NEW.EDC_MEM_NO ELSE /*비회원*/X.EDC_RSVN_MOBLPHON = NEW.EDC_RSVN_MOBLPHON END -- 입력값
			AND Y.COMCD = X.COMCD
			AND Y.ORG_NO = T.ORG_NO
			AND Y.EDC_PRGMID = X.EDC_PRGMID
			AND X.EDC_REQ_SDATE BETWEEN SYYYYMMDD AND EYYYYMMDD;

	IF v_apply_cnt > v_limit_cnt THEN
		SET v_msg = REPLACE('RSVN[강좌전체] 신청가능횟수(LIMITCNT회)가 초과되었습니다.', 'LIMITCNT', v_limit_cnt);
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
	END IF;

	/* 3.2 프로그램카테고리별 신청제한
		고객이 같은 카테고리의 프로그램을 몇번 구매하였는가?. 카테고리명은 무엇인가? 그리고 제한건수는 몇건인가?	*/
	WITH T AS (
		SELECT A.COMCD, A.ORG_NO, A.EDC_RSVNLIMIT_CNT, A.EDC_RSVNLIMIT_PD, B.COM_CTGCD, C.COM_CTGNM, P.EDC_PRGMID
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(P.EDC_SDATE, 1, 6), '01')
					ELSE CONCAT(SUBSTR(P.EDC_SDATE, 1, 4), '0101')
				END AS SYYYYMMDD
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(P.EDC_SDATE, 1, 6), '31')
					ELSE CONCAT(SUBSTR(P.EDC_SDATE, 1, 4), '1231')
				END AS EYYYYMMDD
			FROM EDC_PROGRAM P, EDC_PROGRAM_LIMIT A, EDC_LIMINT_CTGD B, COM_CTGR C
				WHERE P.COMCD = NEW.COMCD
					AND P.EDC_PRGMID = NEW.EDC_PRGMID
					AND A.comcd = P.COMCD
					AND A.org_no = P.ORG_NO
					AND A.EDC_RSVNLIMIT_YN = 'Y'
					AND A.EDC_RSVNLMIT_GBN IN ('2001') /*카테고리별*/
					AND B.COMCD = A.COMCD
					AND B.ORG_NO = A.ORG_NO
					AND B.COM_CTGCD = P.COM_CTGCD
					AND C.COMCD = P.COMCD
					AND C.COM_CTGCD = P.COM_CTGCD
	)
	SELECT T.COM_CTGNM, NVL(T.EDC_RSVNLIMIT_CNT, 999), (NVL(SUM(EDC_VISTNMPR), 0)+1) INTO v_ctgr_nm, v_limit_cnt, v_apply_cnt /* + 1은 이번신청건 포함 */
		FROM T, EDC_RSVN_INFO X, EDC_PROGRAM Y
		WHERE 1 = 1
			AND X.COMCD = T.COMCD
			AND X.EDC_STAT IN ('11', '20')
			AND X.EDC_MEM_NO = NEW.EDC_MEM_NO
			AND Y.COMCD = X.COMCD
			AND Y.ORG_NO = T.ORG_NO
			AND Y.EDC_PRGMID = X.EDC_PRGMID
			AND Y.COM_CTGCD = T.COM_CTGCD
			AND X.EDC_REQ_SDATE BETWEEN SYYYYMMDD AND EYYYYMMDD;

	IF v_apply_cnt > v_limit_cnt THEN
		SET v_msg = REPLACE(REPLACE('RSVN[CTGRNM] 신청가능횟수(LIMITCNT회)가 초과되었습니다.', 'CTGRNM', v_ctgr_nm), 'LIMITCNT', v_limit_cnt);
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
	END IF;

	/* 3.3 고객이 같은 프로그램을 몇번 구매하였는가?. 제한건수는 몇건인가? */
	WITH T AS (
		SELECT A.COMCD, A.ORG_NO, A.EDC_RSVNLIMIT_CNT, A.EDC_RSVNLIMIT_PD, P.EDC_PRGMID
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(P.EDC_SDATE, 1, 6), '01')
					ELSE CONCAT(SUBSTR(P.EDC_SDATE, 1, 4), '0101')
				END AS SYYYYMMDD
			, CASE WHEN NVL(A.EDC_RSVNLIMIT_PD, '1001') = '1001' THEN CONCAT(SUBSTR(P.EDC_SDATE, 1, 6), '31')
					ELSE CONCAT(SUBSTR(P.EDC_SDATE, 1, 4), '1231')
				END AS EYYYYMMDD
			FROM EDC_PROGRAM P, EDC_PROGRAM_LIMIT A, EDC_LIMIT_PRNM B
				WHERE P.COMCD = NEW.COMCD
					AND P.EDC_PRGMID = NEW.EDC_PRGMID
					AND A.comcd = P.COMCD
					AND A.org_no = P.ORG_NO
					AND A.EDC_RSVNLIMIT_YN = 'Y'
					AND A.EDC_RSVNLMIT_GBN IN ('3001')
					AND B.COMCD = P.COMCD
					AND B.ORG_NO = P.ORG_NO
					AND B.EDC_PRGMID = P.EDC_PRGMID
	)
	SELECT NVL(T.EDC_RSVNLIMIT_CNT, 999), (NVL(SUM(EDC_VISTNMPR), 0)+1) INTO v_limit_cnt, v_apply_cnt
		FROM T, EDC_RSVN_INFO X, EDC_PROGRAM Y
		WHERE 1 = 1
			AND X.COMCD = T.COMCD
			AND X.EDC_STAT IN ('11', '20')
			AND X.EDC_MEM_NO = NEW.EDC_MEM_NO
			AND Y.COMCD = X.COMCD
			AND Y.ORG_NO = T.ORG_NO
			AND Y.EDC_PRGMID = X.EDC_PRGMID
			AND X.EDC_REQ_SDATE BETWEEN SYYYYMMDD AND EYYYYMMDD;

	IF v_apply_cnt > v_limit_cnt THEN
		SET v_msg = REPLACE('RSVN[동일강좌] 신청가능횟수(LIMITCNT회)가 초과되었습니다.', 'LIMITCNT', v_limit_cnt);
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
	END IF;

END; //
DELIMITER ;